version: '2'
services:
    devtest-app:
        image: devtest
        external_links:
            - devtest-mysql:mysql
            - devtest-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/devtest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    devtest-mysql:
        extends:
            file: mysql.yml
            service: devtest-mysql
    devtest-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: devtest-elasticsearch
